config/routes.rb
Underdog::Application.routes.draw do
  get "pages/home"

  get "pages/portfolio"

  get "home/index"
  
  root :to => "pages#home"
  match '/portfolio', :to => 'pages#portfolio'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	  @title = "Home"
  end

  def portfolio
  	  @title = "Portfolio"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	#Return a title on a per-page basis.
	def title
		base_title = "Underdog Development"
		if @title.nil? 
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
	<ol id="posts-list" class="hfeed">

		<li><article class="hentry">
			<header>
				<h2 class="entry-title"><a href="#" rel="bookmark" title="Permalink to this POST TITLE">This be the title</a></h2>
			</header>

			<footer class="post-info">
				<abbr class="published" title="2005-10-10T14:07:00-07:00"><!-- YYYYMMDDThh:mm:ss+ZZZZ -->
					10th October 2005
				</abbr>

				<address class="vcard author">
					By <a class="url fn" href="#">Enrique Ramírez</a>

				</address>
			</footer><!-- /.post-info -->

			<div class="entry-content">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque venenatis nunc vitae libero iaculis elementum. Nullam et justo <a href="#">non sapien</a> dapibus blandit nec et leo. Ut ut malesuada tellus.</p>

			</div><!-- /.entry-content -->
		</article></li>

		<li><article class="hentry">
			...
		</article></li>

		<li><article class="hentry">
			...
		</article></li>
	</ol><!-- /#posts-list -->

app/views/layouts/_footer.html.erb
	<footer id="contentinfo" class="body">
		<p>&copy2011 Jamie Hush</p>
	</footer>

app/views/layouts/_header.html.erb
	<header id="banner" class="body">
		<h1>Jamie Hush <strong>Software Developer | Musician | Entrepreneur</strong></h1>
		
		<nav>
			<ul>
				<% if request.fullpath == '/' %>
					<li class="active"><%= link_to "Home", root_path %></li>
				<% else %>
					<li><%= link_to "Home", root_path %></li>
				<% end %>
				
				<% if request.fullpath == '/portfolio' %>
					<li class="active"><%= link_to "Portfolio", portfolio_path %></li>
				<% else %>
					<li><%= link_to "Portfolio", portfolio_path %></li>
				<% end %>
			</ul>
		</nav>
	</header>

app/views/layouts/_stylesheets.html.erb
  <%= stylesheet_link_tag 'main', :media => 'screen'%>  
  <!--[if IE]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  <!--[if lte IE 7]>
	<script src="js/IE8.js" type="text/javascript"></script><![endif]-->
  <!--[if lt IE 7]>
  <link rel="stylesheet" type="text/css" media="all" href="css/ie6.css"/><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= title %></title>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    
</head>

<body id="index" class="home">
    <%= render 'layouts/header' %>

	<%# <aside id="featured" class="body"> %>
		<%# <article> %>
			<%# <hgroup> %>

			<%# <h1>Featured</h1> %>
			
			<%# </hgroup> %>
		<%# </article> %>
	<%# </aside> <!-- /#featured --> %>
	
	<section id="content" class="body">
	
		<%= yield %>
	
	</section><!-- /#content -->
	
    <%= render 'layouts/footer' %>	


</body>
</html>